### ISSUE TITLE
`LOCAL_JACK_LIB` in `SMTG_FindJack.cmake` is not set correctly on windows

### ISSUE THREAD

**Issue by wrist** [steinbergmedia/vst3_cmake#5]
I tried to build `audiohost.exe` on Windows10 64bit machine, but it failed due to `LIBJACK_FOUND` was not set.
My environment is `Windows10 Professional, Version 1909, Build 18363.1316`.

At first,  I installed Jack using installer downloaded from [here](https://jackaudio.org/downloads/).
Then I executed the below cmake command in build directory, 
but `LIBJACK_FOUND was not set` was shown despite of Jack libraries installed.

```sh
$ cmake -DSMTG_ENABLE_USE_OF_JACK=ON -DSMTG_JACK_SDK_PATH="C:\Program Files\JACK2" ..
...
-- Could NOT find LIBJACK (missing: LIBJACK_LIBRARY)
-- LIBJACK_FOUND is not set. If you need it, please install Jack Audio from http://www.jackaudio.org!
-- LIBJACK_FOUND is not set.
...
```

I found the reason was that wrong library path was set in `SMTG_FindJack.cmake`.

https://github.com/steinbergmedia/vst3_cmake/blob/ed8d829631a8913143f5c0f4d5d36a31c412e42c/modules/SMTG_FindJack.cmake#L27-L32

The above lines set `LOCAL_JACK_LIB` as `"${SMTG_JACK_SDK_PATH}/lib/win64"` on 64bit build, 
but current Jack installer for windows try to install 64bit libraries to 

* `C:\Program Files\JACK2\lib`

It also set `LOCAL_JACK_LIB` as `${SMTG_JACK_SDK_PATH}/lib/win32` on 32bit build, 
but Jack installer for windows installs 32bit libraries to 

* `C:\Program FIles\JACK2\lib32` on 64bit windows machine (in my environment, and guessed from [64bit installer code](
https://github.com/jackaudio/jack2/blob/1bba849fee76350a5289ac95eac123795a40cab9/windows/inno/win64.iss#L50-L56))
* `C:\Program Files\JACK2\lib` on 32bit windows machine (guessed from [32bit installer code](https://github.com/jackaudio/jack2/blob/1bba849fee76350a5289ac95eac123795a40cab9/windows/inno/win32.iss#L48-L51))

So finally I fixed this issue by replacing 
`set(LOCAL_JACK_LIB ${SMTG_JACK_SDK_PATH}/lib/win64)` to 
`set(LOCAL_JACK_LIB "${SMTG_JACK_SDK_PATH}/lib")`.

**Comment by ygrabit** [comment]
you can define these instead (fixed in the next update of VST SDK):
 set(PROGRAM_FILE_JACK_INCLUDE "C:/Program Files/JACK2/includes")
 set(PROGRAM_FILE_JACK_LIB "C:/Program Files/JACK2/lib")
