### ISSUE TITLE
For Windows, create destination installation folders if they don't exist

### ISSUE THREAD

**Issue by mortalis13** [steinbergmedia/vst3_cmake#8]
Hi.
After building a project, the final VST3 bundle is installed (creating a symlink) to the `%USERPROFILE%\AppData\Local\Programs\Common\VST3\` folder on Windows 64bit.
But if that folder does not exist, the post-build fails.
Could the `modules/SMTG_SetupVST3LibraryDefaultPath.cmake` be modified so it creates the missing folders automatically?

Thanks.

**Comment by rehans** [comment]
Yes, I will check that asap.
